controller_manager:
  ros__parameters:
    update_rate: 100

    my_group_controller:
      # 暂时都使用位置控制
      type: joint_trajectory_controller/JointTrajectoryController
  
    gripper_group_controller:
      # 
      type: joint_trajectory_controller/JointTrajectoryController

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster


my_group_controller:
  ros__parameters:
    joints:
      - arm_joint1
      - arm_joint2
      - arm_joint3
      - arm_joint4
      - arm_joint5

    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity


gripper_group_controller:
  ros__parameters:
    joints:
      - grip_joint
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
